name: nix

on:
  push:
    branches:
      - main
      - master
      - 'release/**'
    paths-ignore:
      - '**.adoc'
      - '**.md'
      - '*.sh'
      - '.*'
      - 'Brewfile'
      - '_*'
      - 'doc/**'
      - 'flake.lock'
      - '.github/workflows/*.yml'
      - '!.github/workflows/nix.yml'
  pull_request:
    paths-ignore:
      - '**.adoc'
      - '**.md'
      - '*.sh'
      - '.*'
      - 'Brewfile'
      - '_*'
      - 'doc/**'
      - 'flake.lock'
      - '.github/workflows/*.yml'
      - '!.github/workflows/nix.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix build
